---
title: "Formation-R-perfectionnement"
subtitle: "Module Écrire des fonctions avec R"
date: today
date-format: "DD/MM/YYYY"
author: "SSP/DEMESIS"
description: |
  Support de formation R-perfectionnement : Module Écrire des fonctions avec R 
slide-tone: false # for blind readers
chalkboard: false # press the B key to toggle chalkboard
transition: slide
fig-cap-location: bottom
# toc: true
# toc-title: Sommaire
# toc-depth: 1
# toc-float: true
# multiplex: true
execute:
  echo: false
  warning: false
  cache: false
editor:
  render-on-save: true
  markdown: 
    wrap: 72
---

## Avant-propos {.unnumbered}

Ce diaporama de formation a été rédigé dans le but d'être le support
visuel des formations dispensées au
[SSM Agriculture](https://agreste.agriculture.gouv.fr/).

Ces formations s'adressent à des agents qui ont suivi **la formation R
initiation**.

::: callout-note
## Champ couvert par cette formation {.unnumbered}

**Ce support couvre Écrire des fonctions avec R ,** pour en finir avec
les copiés-collés.

Ce module se décompose en plusieurs chapitres :

-   01 - Écrire ses propres fonctions

-   02 - Itération de fonctions

-   03 - Annexes

Ce support est orienté pour être utile aux agents du SSM Agriculture et se
concentre sur une utilisation de R via
[RStudio](https://posit.co/download/rstudio-desktop/) qui est mise à
disposition des agents sur la plateforme interne Cerise basée sur
RStudio Workbench.
:::

## Chapitre 01 : Écrire ses propres fonctions {.unnumbered}

+----------------------------------+----------------------------------+
| -   Quand écrire une fonction ?  | -   Documenter ses fonctions     |
|                                  |                                  |
| -   Comment écrire une fonction  | -   Programmer avec le tidyverse |
|     ?                            |                                  |
|                                  | -   Passer des colonnes en       |
| -   Comment utiliser une         |     paramètres                   |
|     fonction ?                   |                                  |
|                                  | -   Nommer de nouvelles colonnes |
| -   Valeurs par défaut           |                                  |
|                                  | -   Utiliser des chaînes de      |
| -   Exécution conditionnelle     |     caractères                   |
|                                  |                                  |
| -   Portée des variables         | -   Récapitulatif                |
|                                  |                                  |
| -   Stocker ses fonctions        |                                  |
+----------------------------------+----------------------------------+

{{< include 01_quand-ecrire-une-fonction.qmd >}}

{{< include 02_comment-ecrire-une-fonction.qmd >}}

{{< include 03_comment-utiliser-une-fonction.qmd >}}

{{< include 04_valeur-par-defaut.qmd >}}

{{< include 05_execution-conditionnelle.qmd >}}

{{< include 06_portees-variables.qmd >}}

{{< include 07_stocker-fonctions.qmd >}}

{{< include 08_documenter-fonctions.qmd >}}

{{< include 09_programmer-tydyverse.qmd >}}

## Chapitre 02 : Itération de fonctions {.unnumbered}

-   Itération de fonctions : présentation

-   Utilisation de across

-   Utilisation de across : Exemple avec mutate

-   Utilisation de across : Exemple avec summarise

-   Package purrr

-   {purrr} : Itérer sur un vecteur ou une liste

-   {purrr} : Itérer sur deux éléments

-   {purrr} : Généralisation

-   {purrr} : Manipuler des listes

-   {purrr} : Fonctions à effets de bord

{{< include 10_package-across.qmd >}}

{{< include 11_package-purrr.qmd >}}

## Chapitre 03 : Annexes : Pour aller plus loin {.unnumbered}

-   Passer un nombre indéfini de paramètres

-   Retourner plusieurs objets dans une fonction

-   Utiliser plusieurs return dans une fonction

-   Utilisation de across : règle de renommage

-   {purrr} : Contrôler le format de sortie

-   {purrr} : Nommer les éléments d’une liste

-   {purrr} : modifier le comportement d’une fonction

{{< include 12_chapitre03.qmd >}}

# Chapitre 04 : Liens utiles {.unnumbered}

{{< include 13_liens.qmd >}}
